//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public ACTIVIDAD()
        {
            this.CAPACITACION = new HashSet<CAPACITACION>();
        }
    
        public decimal ID_ACTIVIDAD { get; set; }
        public System.DateTime FECHA_ACTIVIDAD { get; set; }
        public string DESCRIPCION_ACTIVIDAD { get; set; }
        public decimal PERSONAL_ID_PERSONAL { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
        public decimal TIPO_ACTIVIDAD_ID_TIPOACTIVI { get; set; }
        public decimal CHECKLIST_ID_CHECKLIST { get; set; }
        public string ACTIVO_ACTIVIDAD { get; set; }
    
        public virtual CHECKLIST CHECKLIST { get; set; }
        public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
        public virtual PERSONAL PERSONAL { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
