//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENTE
    {
        public ASISTENTE()
        {
            this.CAPACITACION = new HashSet<CAPACITACION>();
        }
    
        public decimal ID_ASISTENTE { get; set; }
        public string NOMBRE_ASISTENTE { get; set; }
        public string APELLIDOM_ASISTENTE { get; set; }
        public string APELLIDOP_ASISTENTE { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
    }
}
