//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public decimal ID_CAPACITACION { get; set; }
        public string DESCRIPCION_CAPACITACION { get; set; }
        public decimal ASISTENTE_ID_ASISTENTE { get; set; }
        public decimal ACTIVIDAD_ID_ACTIVIDAD { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual ASISTENTE ASISTENTE { get; set; }
    }
}
