//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public decimal ID_CAPACITACION { get; set; }
        public string DESCRIPCION_CAPACITACION { get; set; }
        public decimal ASISTENTE_ID_ASISTENTE { get; set; }
        public decimal ACTIVIDAD_ID_ACTIVIDAD { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual ASISTENTE ASISTENTE { get; set; }
    }
}
