//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST
    {
        public CHECKLIST()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
            this.OPCION_CHECKLIST = new HashSet<OPCION_CHECKLIST>();
        }
    
        public decimal ID_CHECKLIST { get; set; }
        public string NOMBRE_CHECKLIST { get; set; }
        public string DESCRIPCION_CHECKLIST { get; set; }
    
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual ICollection<OPCION_CHECKLIST> OPCION_CHECKLIST { get; set; }
    }
}
