//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
            this.ASISTENTE = new HashSet<ASISTENTE>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.REPORTAR = new HashSet<REPORTAR>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string APELLIDO_CLIENTE { get; set; }
        public string TELEFONO_CLIENTE { get; set; }
        public string DIREC_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public decimal RUBRO_ID_RUBRO { get; set; }
        public string ACTIVO_CLIENTE { get; set; }
        public decimal USUARIO_ID_USUARIO { get; set; }
    
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual ICollection<ASISTENTE> ASISTENTE { get; set; }
        public virtual RUBRO RUBRO { get; set; }
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual ICollection<REPORTAR> REPORTAR { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
