//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal ID_CONTRATO { get; set; }
        public System.DateTime FECHA_INICIO_CONTRATO { get; set; }
        public System.DateTime FECHA_FIN_CONTRATO { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
        public string ACTIVO { get; set; }
        public decimal PLAN_ID_PLAN { get; set; }
    
        public virtual PLAN PLAN { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
