//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public decimal ID_DETALLE_FACTURA { get; set; }
        public string RUT_CLIENTE_FACTURA { get; set; }
        public System.DateTime FECHA_VENTA_FACTURA { get; set; }
        public System.DateTime FECHA_VENC_FACTURA { get; set; }
        public string DETALLE_FACTURA1 { get; set; }
        public decimal MONTO_FACTURA { get; set; }
        public decimal ACTIVIDAD_ID_ACTIVIDAD { get; set; }
        public decimal FACTURA_ID_FACTURA { get; set; }
        public decimal CONTRATO_ID_CONTRATO { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual FACTURA FACTURA { get; set; }
    }
}
