//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public decimal ID_FACTURA { get; set; }
        public decimal CONTRATO_ID_CONTRATO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string PAGADO { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal IVA { get; set; }
        public string NOMBRE_PLAN { get; set; }
        public decimal VALOR_PLAN { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string CORREO_ELECTRONICO_CLIENTE { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
    }
}
