//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_CHECKLIST
    {
        public decimal ID_OPCION_CHECKLIST { get; set; }
        public string NOMBRE_OPCION { get; set; }
        public string DESCRIPCION_OPCION { get; set; }
        public string ESTADO { get; set; }
        public decimal CHECKLIST_ID_CHECKLIST { get; set; }
    
        public virtual CHECKLIST CHECKLIST { get; set; }
    }
}
