//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_CHECKLIST
    {
        public decimal ID_OPCION_CHECKLIST { get; set; }
        public string NOMBRE_OPCION { get; set; }
        public string DESCRIPCION_OPCION { get; set; }
        public string ESTADO { get; set; }
        public decimal CHECKLIST_ID_CHECKLIST { get; set; }
    
        public virtual CHECKLIST CHECKLIST { get; set; }
    }
}
