//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN
    {
        public PLAN()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public decimal ID_PLAN { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALOR { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
