//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTAR
    {
        public decimal ID_REPORTAR { get; set; }
        public string DETALLE_REPORTAR { get; set; }
        public System.DateTime FECHA_REPORTAR { get; set; }
        public string ESTADO_REPORTAR { get; set; }
        public decimal TIPO_REPORTAR_ID_TIPO_REPORTAR { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_REPORTAR TIPO_REPORTAR { get; set; }
    }
}
