//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTAR
    {
        public decimal ID_REPORTAR { get; set; }
        public string DETALLE_REPORTAR { get; set; }
        public System.DateTime FECHA_REPORTAR { get; set; }
        public string ESTADO_REPORTAR { get; set; }
        public decimal TIPO_REPORTAR_ID_TIPO_REPORTAR { get; set; }
        public decimal CLIENTE_ID_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_REPORTAR TIPO_REPORTAR { get; set; }
    }
}
