//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRO
    {
        public RUBRO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public decimal ID_RUBRO { get; set; }
        public string NOMBRE_RUBRO { get; set; }
        public string DESC_RUBRO { get; set; }
        public string ACTIVO_RUBRO { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
