//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_REPORTAR
    {
        public TIPO_REPORTAR()
        {
            this.REPORTAR = new HashSet<REPORTAR>();
        }
    
        public decimal ID_TIPO_REPORTAR { get; set; }
        public string TIPO_REPORTAR1 { get; set; }
    
        public virtual ICollection<REPORTAR> REPORTAR { get; set; }
    }
}
