//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SOLICITUD
    {
        public TIPO_SOLICITUD()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_TIPOSOLICI { get; set; }
        public string NOMBRE_TIPOSOLICITUD { get; set; }
        public string DESCRIPCION_TIPOSOLICITUD { get; set; }
    
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
