//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PERSONAL
    {
        public TIPO_PERSONAL()
        {
            this.PERSONAL = new HashSet<PERSONAL>();
        }
    
        public decimal ID_TIPOPERSONAL { get; set; }
        public string TIPO_PERSONAL1 { get; set; }
        public string DESC_TIPOPERSONAL { get; set; }
    
        public virtual ICollection<PERSONAL> PERSONAL { get; set; }
    }
}
