//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PERSONAL = new HashSet<PERSONAL>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public string USUARIO1 { get; set; }
        public string PASSWORD { get; set; }
        public decimal TIPO_USUARIO { get; set; }
    
        public virtual ICollection<PERSONAL> PERSONAL { get; set; }
        public virtual TIPO_PERSONAL TIPO_PERSONAL { get; set; }
    }
}
